services:
  mediamtx:
    image: bluenviron/mediamtx:1
    container_name: mediamtx
    environment:
      MTX_WEBRTCALLOWORIGIN: "*"
      MTX_RTSPTRANSPORTS: "tcp"
      MTX_WEBRTCADDITIONALHOSTS: "127.0.0.1,host.docker.internal,192.168.0.106"
    ports:
      - "8554:8554"   # RTSP
      - "8888:8888"   # Web UI
      - "8889:8889"   # WHIP/WHEP
      - "8189:8189/udp"
      # - "1935:1935" # only if you need RTMP
    restart: unless-stopped
  backend:
    build:

      context: ./stream_platform
      dockerfile: Dockerfile
    container_name: stream_platform_backend
    depends_on:
      - mediamtx
    environment:
        RTSP_URL: "rtsp://mediamtx:8554/mystream3"
    ports:
      - "8000:8000"
    restart: unless-stopped